### ISSUE TITLE
Crash with Sodium 0.5.2 and Puzzles Lib v8.0.24

### ISSUE THREAD

**Issue by cntrik** [ishland/EarlyLoadingScreen#10] opened 2023-09-12 03:36 UTC
Fabric Loader 0.14.22
Minecraft Version 1.20.1

[crashlog](https://gist.github.com/Afrocntrik/dd6bf2668dfa14aeb53d7106dd5636d6)

**Comment by ishland** [comment] 2023-09-12 10:03
Duplicate of #9

**Closed as completed by ishland** 2023-09-12 10:03 UTC
